### ISSUE TITLE
Reopened issues result in Error

### ISSUE THREAD

**Issue by jonasnick** [nbigaouette/gitlab-api-rs#14]
Hi,

I'm getting the following error on a reopened issue:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Msg("cannot get query projects/71/issues?state=opened....\"state\":\"reopened\"....., State { next_error: Some(Syntax(UnknownVariant("reopened"), 1, 245)), backtrace: None })), backtrace: None })', ../src/libcore/result.rs:837
```
backtrace:
```
0:     0x564886c715b1 - backtrace::backtrace::libunwind::trace
                        at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.0/src/backtrace/mod.rs:90
                         - backtrace::backtrace::trace<closure>
                        at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.0/src/backtrace/mod.rs:42
   1:     0x564886c723e8 - backtrace::capture::{{impl}}::new
                        at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.0/src/lib.rs:101
   2:     0x564886c68d41 - error_chain::make_backtrace
                        at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/error-chain-0.7.2/src/lib.rs:411
   3:     0x564886a2c512 - core::option::{{impl}}::or_else<alloc::arc::Arc<backtrace::capture::Backtrace>,fn() -> core::option::Option<alloc::arc::Arc<backtrace::capture::Backtrace>>>
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libcore/option.rs:631
   4:     0x564886a23686 - error_chain::{{impl}}::new<gitlab_api::errors::Error>
                        at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/error-chain-0.7.2/src/lib.rs:476
   5:     0x564886b9b6f7 - gitlab_api::errors::{{impl}}::chain_err::{{closure}}<collections::vec::Vec<gitlab_api::Issue>,serde_json::error::Error,closure,collections::string::String>
                        at /home/user/.cargo/git/checkouts/gitlab-api-rs-4a70531d0adf7eec/b2aa738a25d574aa51af2ab356bdb5803e18a1a3/src/lib.rs:22
   6:     0x564886a3dc6b - core::result::{{impl}}::map_err<collections::vec::Vec<gitlab_api::Issue>,serde_json::error::Error,gitlab_api::errors::Error,closure>
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libcore/result.rs:494
   7:     0x564886b2c7cb - gitlab_api::errors::{{impl}}::chain_err<collections::vec::Vec<gitlab_api::Issue>,serde_json::error::Error,closure,collections::string::String>
                        at /home/user/.cargo/git/checkouts/gitlab-api-rs-4a70531d0adf7eec/b2aa738a25d574aa51af2ab356bdb5803e18a1a3/src/lib.rs:22
   8:     0x564886b2891e - gitlab_api::gitlab::{{impl}}::get<collections::vec::Vec<gitlab_api::Issue>,core::option::Option<u16>>
                        at /home/user/.cargo/git/checkouts/gitlab-api-rs-4a70531d0adf7eec/b2aa738a25d574aa51af2ab356bdb5803e18a1a3/src/gitlab.rs:205
   9:     0x564886b2af46 - gitlab_api::issues::project::{{impl}}::list
                        at /home/user/.cargo/git/checkouts/gitlab-api-rs-4a70531d0adf7eec/b2aa738a25d574aa51af2ab356bdb5803e18a1a3/src/issues/project.rs:58
  10:     0x564886a1e456 - collect_repo_metadata::get_issues
```

Thanks

**Comment by nbigaouette** [comment]
I've just fixed this. I also added an example to get a project/merge request/issue `id` from the `iid`:

```
> export GITLAB_HOSTNAME=gitlab.com
> export GITLAB_TOKEN=XXXXXXXXXXXXXXXXXXXX
> cargo run --example get_id_issue -- -n nbigaouette1 -p gitlab-api-rs --id 3
Id for nbigaouette1/gitlab-api-rs#3: 4138506
```
